import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/header";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} antialiased dark`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
