import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/header";
import { AuthProvider } from "./_contexts/auth-context";
import { Toaster } from "./_components/ui/sonner";
import React from "react"; // Import necessário para React.StrictMode

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} antialiased dark`}>
        <React.StrictMode>
          <Toaster />
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}
